### ISSUE TITLE
help on installing pixelos on tapas 

### ISSUE THREAD

**Issue by ayoub-ennaciri** [rn124g-development/PixelOS#1]
hi , sry for any disruption i have been trying to install you rom on my redme note 12 tapas , but i just could not do it , or install any other rom , i have twrp installed on a partion and orangefox on the b partion , when i run the install on you rom on the a partion it starts and then stops arond 40 50% and the it shows alot of errors and i reboot to recovery that sends me to the b partition with no os being installed 
any help would be appreciate.

**Comment by AliHasan7671** [comment]
Use offcial orangefox on both slots, and follow this:
flash early HyperOS firmware > Flash ROM > reboot to recovery > flash the firmware again > Flash ROM > Reboot.

Join telegram group if needed further help https://t.me/topsecretgroup
