### ISSUE TITLE
Display Refresh Rate?

### ISSUE THREAD

**Issue by aftwro** [rn124g-development/PixelOS#2]
I recently just now installed PixelOS on Tapas 23021RAAEG.
I messed around with the developer options and device specific options to get 120hz working, but it's just locked at 60?
I'm not sure what I'm supposed to do next to get 120hz.

Magisk is installed if that matters.

**Comment by AliHasan7671** [comment]
120Hz works just fine, the option is under Settings > System > Device Specific Settings.

**Comment by aftwro** [comment]
Nevermind, I did some messing around and it worked.

I now have another question: I noticed some roms have the charging status on the lock screen, is there anyway to get that? It's an awfully useful feature.

Edit: Another thing I noticed, the whole system is sluggish and slow under 60Hz, 120Hz makes it extremely fast and snappy.

**Comment by AliHasan7671** [comment]
Charging status: No
And use 120Hz then, I mean you purchased 120Hz display device, so use it. 60Hz always feels sluggish on 120Hz displays.
